## cartoframes: Augmenting from the Data Obs

In [1]:
import pandas as pd
import cartoframes
USERNAME = 'eschbacher'
APIKEY = '8e92c06c9a91f8d3c00455109e8e609ee4096d62'
df = pd.read_carto(username=USERNAME,
                   api_key=APIKEY,
                   tablename='brooklyn_poverty')
df.head()

Named map name: brooklyn_poverty_1489501989_500104

,geoid,high_school_diploma_2011_2015,median_income_2011_2015,new_column,poverty_2011_2015,poverty_count,poverty_per_pop,the_geom,the_geom_webmercator,total_pop_2011_2015,total_population
cartodb_id,,,,,,,,,,,
155,360470021001,0.037004,208036.0,7698.083032,0.075573,46.242950,0.039728,0103000020E6100000010000007C0000004BE2AC889A7F...,0103000020110F0000010000007C0000006BB2B13AE66B...,7568.986964,1164.0
734,360470274002,0.292395,42266.0,12358.371504,0.146278,342.812734,0.210186,0103000020E6100000010000000F00000066BCADF4DA7F...,0103000020110F0000010000000F0000000D7705A8536C...,18914.903234,1631.0
735,360470275001,0.258389,55990.0,14467.214765,0.251098,172.323529,0.151560,0103000020E61000000100000007000000EB89AE0B3F7C...,0103000020110F000001000000070000003CB24E4D3266...,26814.609541,1137.0
736,360470275002,0.258389,55990.0,14467.214765,0.251098,383.567627,0.273977,0103000020E6100000010000000A00000052B7B3AF3C7C...,0103000020110F0000010000000A0000001F11634B2E66...,26814.318226,1400.0
737,360470275003,0.258389,55990.0,14467.214765,0.251098,132.253870,0.149102,0103000020E61000000100000009000000E868554B3A7C...,0103000020110F0000010000000900000071B8373B2A66...,26814.025271,887.0

In [18]:
df.carto_map(interactive=False, color={'colname': 'poverty_per_pop'},
             figsize=(240, 240))

In [19]:
# total pop, high school diploma (normalized), median income, poverty status (normalized)
# TODO: add optional_colname
# TODO: aggregate points in polys given extent (using do boundaries of specified levels)
data_obs_measures = [{'numer_id': 'us.census.acs.B01003001'},
                     {'numer_id': 'us.census.acs.B15003017', 'denominator': 'predenominated'},
                     {'numer_id': 'us.census.acs.B19013001'},
                     {'numer_id': 'us.census.acs.B17001002', 'denominator': 'predenominated'}]
df.carto_do_augment(data_obs_measures)
df.head(10)

,category,geoid,poverty_count,poverty_per_pop,the_geom,the_geom_webmercator,total_population,high_school_diploma_2011_2015,median_income_2011_2015,poverty_2011_2015,total_pop_2011_2015
cartodb_id,,,,,,,,,,,
538,census tract,360470198002,0.000000,0.000000,0103000020E6100000010000000B0000004D64E6029780...,0103000020110F0000010000000B00000029C16D16936D...,1016.0,0.224012,61875.0,0.164813,14682.561171
539,census tract,360470199001,23.333333,0.040023,0103000020E61000000100000007000000F886C267EB7D...,0103000020110F000001000000070000007326FCE90969...,583.0,0.126472,67656.0,0.139714,15155.355115
540,census tract,360470199002,11.963526,0.014554,0103000020E6100000010000000A000000C4B0C398F47D...,0103000020110F0000010000000A0000001FCACC861969...,822.0,0.126472,67656.0,0.139714,15155.023158
541,census tract,360470232002,421.324415,0.333063,0103000020E61000000100000009000000323CF6B3587F...,0103000020110F000001000000090000003C18AA68766B...,1265.0,0.361477,33801.0,0.443496,25414.064140
542,census tract,360470215004,404.575805,0.150792,0103000020E6100000010000000E000000D5CA845FEA7D...,0103000020110F0000010000000E000000F60F25290869...,2683.0,0.137087,61723.0,0.137461,33718.624902
543,census tract,360470199003,24.400000,0.059367,0103000020E6100000010000000C000000FE976BD1027E...,0103000020110F0000010000000C000000F2FFD1AE3169...,411.0,0.126472,67656.0,0.139714,15154.714405
544,census tract,360470199004,196.662420,0.185706,0103000020E6100000010000000800000023F3C81F0C7E...,0103000020110F000001000000080000001FA6817D4169...,1059.0,0.126472,67656.0,0.139714,15155.308207
545,census tract,360470200001,166.635135,0.129981,0103000020E610000001000000090000004FE61F7D9380...,0103000020110F00000100000009000000472BAC1A8D6D...,1282.0,0.264591,58000.0,0.148014,16432.286811
546,census tract,360470200002,144.247191,0.160275,0103000020E6100000010000000B0000004DA1F31ABB80...,0103000020110F0000010000000B000000A61C9665D06D...,900.0,0.264591,58000.0,0.148014,16431.821371
547,census tract,360470201001,62.643564,0.096079,0103000020E61000000100000009000000B519A721AA7D...,0103000020110F00000100000009000000F9BC2F0A9B68...,652.0,0.073720,84844.0,0.075832,22157.907293

In [2]:
df.carto_map(interactive=True, 
             color={'colname': 'high_school_diploma_2011_2015', 'ramp': 'Mint'},
             debug=True)

#layer { polygon-fill: ramp([high_school_diploma_2011_2015], cartocolor(Mint), quantiles()); line-width: 0.5; line-color: #FFF; line-opacity: 0.5; }
/files/cartoframes.html?username=eschbacher&tablename=brooklyn_poverty_notnull_geoms&cartocss=%23layer+%7B+polygon-fill%3A+ramp%28%5Bhigh_school_diploma_2011_2015%5D%2C+cartocolor%28Mint%29%2C+quantiles%28%29%29%3B+line-width%3A+0.5%3B+line-color%3A+%23FFF%3B+line-opacity%3A+0.5%3B+%7D&basemap=None&bounds=40.7391679594665%2C-73.8334120112118%2C40.5695860392157%2C-74.0419259959785&q=%257B%250A%2520%2520%2520%2520%2520%2520%2522user_name%2522%253A%2520%2522eschbacher%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522type%2522%253A%2520%2522namedmap%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522named_map%2522%253A%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2522name%2522%253A%2520%2522brooklyn_poverty_notnull_geoms_1489163766_249506%2522%250A%2520%2520%2520%2520%2520%2520%257D%252C%250A%2520%2520%2520%2520%2520%2520%2522subdomains%2522%253A%2520%255B%2520%2522a%2522%252C%2520%2522b%2522%252C%2520%2522c%2522%2520%255D%250A%2520%2520%2520%2520%2520%2520%257D

In [3]:
import pandas as pd
import cartoframes
USERNAME = 'eschbacher'
APIKEY = '8e92c06c9a91f8d3c00455109e8e609ee4096d62'
df = pd.read_carto(username=USERNAME,
                   api_key=APIKEY,
                   query='select * from all_month_3 limit 100',
                   tablename='test_table')
df.head()

Named map name: test_table_1489165542_8294559

,created_at,depth,dmin,gap,id,latitude,longitude,mag,magtype,net,nst,place,rms,the_geom,the_geom_webmercator,time,type,updated,updated_at
cartodb_id,,,,,,,,,,,,,,,,,,,
601,2015-02-17 18:36:45,8.5026,0.045,81.77000,nn00482982,39.3918,-119.8228,0.22,ml,nn,11.0,"15km S of Reno, Nevada",0.1353,0101000020E610000086C954C1A8F45DC052499D8026B2...,0101000020110F00000D079BA2FE7069C1A5D4B27DF739...,2015-02-15 01:35:33,earthquake,2015-02-15 17:21:54,2015-02-17 18:36:45
1287,2015-02-17 18:36:45,25.6000,NaN,248.39998,ak11509593,53.6875,-164.4147,2.30,ml,ak,15.0,"102km ESE of Akutan, Alaska",0.3500,0101000020E6100000D734EF38458D64C00000000000D8...,0101000020110F0000CA46ED0A667471C1535C38528620...,2015-02-12 11:25:16,earthquake,2015-02-16 20:58:06,2015-02-17 18:36:45
1383,2015-02-17 18:36:45,1.3000,NaN,NaN,ak11506296,61.2932,-152.2508,2.40,ml,ak,NaN,"84km NW of Nikiski, Alaska",0.6400,0101000020E6100000C7BAB88D060863C0F697DD9387A5...,0101000020110F0000DB3E7618D02970C1A4DC3E68DA94...,2015-02-12 03:37:53,earthquake,2015-02-16 21:00:35,2015-02-17 18:36:45
1940,2015-02-17 18:36:45,22.8000,NaN,NaN,ak11505769,60.6334,-149.4696,1.80,ml,ak,NaN,"45km WSW of Whittier, Alaska",0.5900,0101000020E6100000744694F606AF62C0A9A44E401351...,0101000020110F000075B85AF873BC6FC12C564EFEF54A...,2015-02-10 05:22:34,earthquake,2015-02-10 05:44:46,2015-02-17 18:36:45
2817,2015-02-17 18:36:45,4.6000,NaN,NaN,ak11506661,51.5992,-173.7764,1.70,ml,ak,NaN,"72km SSE of Atka, Alaska",0.3200,0101000020E6100000A913D044D8B865C0B1E1E995B2CC...,0101000020110F0000281AC2C5D37272C1F48C31664AAA...,2015-02-06 16:04:07,earthquake,2015-02-12 18:15:29,2015-02-17 18:36:45

In [4]:
len(df)

100